services:
  docs:
    image: opswat_backend_local_docs
    container_name: opswat_backend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./opswat_backend:/app/opswat_backend:z
    ports:
      - '9000:9000'
    command: /start-docs
