# Generated by Django 5.1.11 on 2025-08-03 14:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('repo_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GitHubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('activity_type', models.CharField(choices=[('push_commits', 'Push Commits'), ('create_pr', 'Create Pull Request'), ('merge_pr', 'Merge Pull Request'), ('create_release', 'Create Release')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('username', models.CharField(max_length=100)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_activities', to='activities.repository')),
            ],
            options={
                'verbose_name_plural': 'GitHub activities',
                'ordering': ['-created'],
            },
        ),
    ]
