# Generated by Django 5.1.11 on 2025-08-03 11:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('CHORE', 'Chore'), ('FEATURE', 'Feature'), ('BUG', 'Bug')], default='FEATURE', max_length=20)),
                ('status', models.CharField(choices=[('UNSTARTED', 'Unstarted'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELIVERED', 'Delivered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='UNSTARTED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
